# template.yaml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a SAM infrastructure template for data-api which is a Serverless API for 
  composing and managing Lists used before processing in glue Crawler.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: prod
  ListerTableName:
    Type: String
    Default: lots-of-lists

Resources:
  ListerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.app
      Runtime: python3.9
      Environment:
        Variables:
          TABLE_NAME: !Ref ListerTableName
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ListerTable
      Events:
        FetchLists:
          Type: Api
          Properties:
            Path: /lists
            Method: get
           
        CreateList:
          Type: Api
          Properties:
            Path: /lists
            Method: post
           
        FetchList:
          Type: Api
          Properties:
            Path: /lists/{id}
            Method: get
           
        UpdateList:
          Type: Api
          Properties:
            Path: /lists/{id}
            Method: put
           
        DeleteList:
          Type: Api
          Properties:
            Path: /lists/{id}
            Method: delete
          
  ListerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ListerTableName
      AttributeDefinitions:
        - AttributeName: listId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: listId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ListsApi:
    Description: "API Gateway endpoint URL for Prod stage for Lots Of Lists function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lists"
  ListerFunction:
    Description: "Lots Of Lists Lambda Function ARN"
    Value: !GetAtt ListerFunction.Arn
  ListerFunctionIamRole:
    Description: "Implicit IAM Role created for Lots Of Lists function"
    Value: !GetAtt ListerFunctionRole.Arn
